name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REF: github.com/${{github.repository}}
      MYEMAIL: zhewana@qq.com
      MYNAME: ${{github.repository_owner}}
      REPO_NAME: ${{ github.event.repository.name }}
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - uses: bwoodsend/setup-winlibs-action@v1

    - name: Install dependencies and build all
      run: |
        ls
        ./pack_python_files.bat
        ls
    - name: Push all files to master branch
      run: |
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}-bot"
        git remote add ${REPO_NAME} "https://${TOKEN}@${REF}"
        git add .
        git commit -m "$ZhTools-bot: built all exe." || exit 0
        git push --force ${REPO_NAME}